build(deps): bump yaml and lint-staged (#1303)
Bumps [yaml](https://github.com/eemeli/yaml) to 2.8.3 and updates
ancestor dependency
[lint-staged](https://github.com/lint-staged/lint-staged). These
dependencies need to be updated together.

Updates `yaml` from 2.6.1 to 2.8.3
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/eemeli/yaml/releases">yaml's
releases</a>.</em></p>
<blockquote>
<h2>v2.8.3</h2>
<ul>
<li>Add <code>trailingComma</code> ToString option for multiline flow
formatting (<a
href="https://redirect.github.com/eemeli/yaml/issues/670">#670</a>)</li>
<li>Catch stack overflow during node composition (1e84ebb)</li>
</ul>
<h2>v2.8.2</h2>
<ul>
<li>Serialize -0 as -0 (<a
href="https://redirect.github.com/eemeli/yaml/issues/638">#638</a>)</li>
<li>Do not double newlines for empty map values (<a
href="https://redirect.github.com/eemeli/yaml/issues/642">#642</a>)</li>
</ul>
<h2>v2.8.1</h2>
<ul>
<li>Preserve empty block literals (<a
href="https://redirect.github.com/eemeli/yaml/issues/634">#634</a>)</li>
</ul>
<h2>v2.8.0</h2>
<ul>
<li>Add node cache for faster alias resolution (<a
href="https://redirect.github.com/eemeli/yaml/issues/612">#612</a>)</li>
<li>Re-introduce compatibility with Node.js 14.6 (<a
href="https://redirect.github.com/eemeli/yaml/issues/614">#614</a>)</li>
<li>Add <code>--merge</code> option to CLI tool (<a
href="https://redirect.github.com/eemeli/yaml/issues/611">#611</a>)</li>
<li>Improve error for tag resolution error on null value (<a
href="https://redirect.github.com/eemeli/yaml/issues/616">#616</a>)</li>
<li>Allow empty string as plain scalar representation, for failsafe
schema (<a
href="https://redirect.github.com/eemeli/yaml/issues/616">#616</a>)</li>
<li>docs: include cli example (<a
href="https://redirect.github.com/eemeli/yaml/issues/617">#617</a>)</li>
</ul>
<h2>v2.7.1</h2>
<ul>
<li>Do not allow seq with single-line collection value on same line with
map key (<a
href="https://redirect.github.com/eemeli/yaml/issues/603">#603</a>)</li>
<li>Improve warning &amp; avoid TypeError on bad YAML 1.1 nodes (<a
href="https://redirect.github.com/eemeli/yaml/issues/610">#610</a>)</li>
</ul>
<h2>v2.7.0</h2>
<p>The library is now available on JSR as <a
href="https://jsr.io/@eemeli/yaml"><code>@​eemeli/yaml</code></a> and on
deno.land/x as <a href="https://deno.land/x/yaml">yaml</a>. In addition
to Node.js and browsers, it should work in Deno, Bun, and Cloudflare
Workers.</p>
<ul>
<li>Use .ts extension in all relative imports (<a
href="https://redirect.github.com/eemeli/yaml/issues/591">#591</a>)</li>
<li>Ignore newline after block seq indicator as space before value (<a
href="https://redirect.github.com/eemeli/yaml/issues/590">#590</a>)</li>
<li>Require Node.js 14.18 or later (was 14.6) (<a
href="https://redirect.github.com/eemeli/yaml/issues/598">#598</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/eemeli/yaml/commit/ce14587484822bffb0f7d31aefedcaf2dc0d0387"><code>ce14587</code></a>
2.8.3</li>
<li><a
href="https://github.com/eemeli/yaml/commit/1e84ebbea7ec35011a4c61bbb820a529ee4f359b"><code>1e84ebb</code></a>
fix: Catch stack overflow during node composition</li>
<li><a
href="https://github.com/eemeli/yaml/commit/6b24090280eaaab5040112bba41ccef57f39c2d5"><code>6b24090</code></a>
ci: Include Prettier check in lint action</li>
<li><a
href="https://github.com/eemeli/yaml/commit/9424dee38c85163fad53ac27533c7c4bdaf7495d"><code>9424dee</code></a>
chore: Refresh lockfile</li>
<li><a
href="https://github.com/eemeli/yaml/commit/d1aca82bc15a4c261bdc58561d32189a5d3a45ef"><code>d1aca82</code></a>
Add trailingComma ToString option for multiline flow formatting (<a
href="https://redirect.github.com/eemeli/yaml/issues/670">#670</a>)</li>
<li><a
href="https://github.com/eemeli/yaml/commit/43215099f7fcdac422d778c15e70d83c691b0e41"><code>4321509</code></a>
ci: Drop the branch filter from GitHub PR actions</li>
<li><a
href="https://github.com/eemeli/yaml/commit/47207d0fc7d4f863cd5fbdcff1378637bd93e847"><code>47207d0</code></a>
chore: Update docs-slate</li>
<li><a
href="https://github.com/eemeli/yaml/commit/5212faeed5936d1fa291d2f28672e4a96e2c2c5d"><code>5212fae</code></a>
chore: Update docs-slate</li>
<li><a
href="https://github.com/eemeli/yaml/commit/086fa6b5bae325da18734750cddee231ce578930"><code>086fa6b</code></a>
2.8.2</li>
<li><a
href="https://github.com/eemeli/yaml/commit/95f01e98032ddf199b42bb3ba0737303b35ef752"><code>95f01e9</code></a>
chore: Add funding to package.json</li>
<li>Additional commits viewable in <a
href="https://github.com/eemeli/yaml/compare/v2.6.1...v2.8.3">compare
view</a></li>
</ul>
</details>
<br />

Updates `lint-staged` from 15.3.0 to 15.5.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/lint-staged/lint-staged/releases">lint-staged's
releases</a>.</em></p>
<blockquote>
<h2>v15.5.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1544">#1544</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/556132176afce1701b4766c00ffd23159d437cb4"><code>5561321</code></a>
Thanks <a
href="https://github.com/YimingIsCOLD"><code>@​YimingIsCOLD</code></a>!
- Correctly handle colon (<code>:</code>) characters in staged
filenames.</li>
</ul>
<h2>v15.5.1</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1533">#1533</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/5d535349958a939cd17d87180196bb2b9dfc452b"><code>5d53534</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Improve listing of staged files so that <em>lint-staged</em> doesn't
crash when encountering an uninitialized submodule. This should result
in less errors like:</p>
<pre><code>✖ Failed to get staged files!
</code></pre>
</li>
</ul>
<h2>v15.5.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1526">#1526</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Lint-staged no longer resets to the original state when preventing an
empty git commit. This happens when your configured tasks reset all the
staged changes, typically when trying to commit formatting changes which
conflict with your linter setup like ESLint or Prettier.</p>
<h3>Example with Prettier</h3>
<p>By default Prettier <a
href="https://prettier.io/docs/rationale#strings">prefers double
quotes</a>.</p>
<h4>Previously</h4>
<ol>
<li>Stage <code>file.js</code> with only double quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails,
cancels the commit, and resets back to the original state</li>
<li>Commit was not done, original state is restored and single quotes
<code>'</code> are staged</li>
</ol>
<h4>Now</h4>
<ol>
<li>Stage <code>file.js</code> with only double-quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails and
cancels the commit</li>
<li>Commit was not done, and there are no staged changes</li>
</ol>
</li>
</ul>
<h2>v15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a>
Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>!
- Adjust TypeScript types for the default export so that it can be used
as a value without error TS2693.</li>
</ul>
<h2>v15.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1509">#1509</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18"><code>8827ebf</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Change <em>lint-staged</em>'s dependencies to use <a
href="https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004">caret
(<code>^</code>) ranges</a> instead of <a
href="https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1">tilde
(<code>~</code>)</a>. This makes it easier for package managers to
perform dependency management when minor-level updates are also
permitted instead of just patch-level.</li>
</ul>
<h2>v15.4.1</h2>
<h3>Patch Changes</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/lint-staged/lint-staged/blob/main/CHANGELOG.md">lint-staged's
changelog</a>.</em></p>
<blockquote>
<h2>15.5.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1544">#1544</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/556132176afce1701b4766c00ffd23159d437cb4"><code>5561321</code></a>
Thanks <a
href="https://github.com/YimingIsCOLD"><code>@​YimingIsCOLD</code></a>!
- Correctly handle colon (<code>:</code>) characters in staged
filenames.</li>
</ul>
<h2>15.5.1</h2>
<h3>Patch Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1533">#1533</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/5d535349958a939cd17d87180196bb2b9dfc452b"><code>5d53534</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Improve listing of staged files so that <em>lint-staged</em> doesn't
crash when encountering an uninitialized submodule. This should result
in less errors like:</p>
<pre><code>✖ Failed to get staged files!
</code></pre>
</li>
</ul>
<h2>15.5.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1526">#1526</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/630af5fb48ed43eb6ccaefa7a9d9612309023b6f"><code>630af5f</code></a>
Thanks <a href="https://github.com/iiroj"><code>@​iiroj</code></a>! -
Lint-staged no longer resets to the original state when preventing an
empty git commit. This happens when your configured tasks reset all the
staged changes, typically when trying to commit formatting changes which
conflict with your linter setup like ESLint or Prettier.</p>
<h3>Example with Prettier</h3>
<p>By default Prettier <a
href="https://prettier.io/docs/rationale#strings">prefers double
quotes</a>.</p>
<h4>Previously</h4>
<ol>
<li>Stage <code>file.js</code> with only double quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails,
cancels the commit, and resets back to the original state</li>
<li>Commit was not done, original state is restored and single quotes
<code>'</code> are staged</li>
</ol>
<h4>Now</h4>
<ol>
<li>Stage <code>file.js</code> with only double-quotes
<code>&quot;</code> changed to <code>'</code></li>
<li>Run <code>git commit -am &quot;I don't like double
quotes&quot;</code></li>
<li><em>Lint-staged</em> runs <code>prettier --write file.js</code>,
converting all the <code>'</code> back to <code>&quot;</code></li>
<li>Because there are now no changes, <em>lint-staged</em> fails and
cancels the commit</li>
<li>Commit was not done, and there are no staged changes</li>
</ol>
</li>
</ul>
<h2>15.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/lint-staged/lint-staged/pull/1512">#1512</a>
<a
href="https://github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1"><code>cbfed1d</code></a>
Thanks <a href="https://github.com/tarik02"><code>@​tarik02</code></a>!
- Adjust TypeScript types for the default export so that it can be used
as a value without error TS2693.</li>
</ul>
<h2>15.4.2</h2>
<h3>Patch Changes</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/8e913024b3d49f85098dcacaaf16bfca8f538db0"><code>8e91302</code></a>
chore(changeset): release</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/64148fd3f926f4cda3ec54ac5fe41cb0568bd00e"><code>64148fd</code></a>
Merge pull request <a
href="https://redirect.github.com/lint-staged/lint-staged/issues/1545">#1545</a>
from lint-staged/revert-v16-changes</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/46f47b2581002622d3f2cb5c636541a155753ce8"><code>46f47b2</code></a>
Revert &quot;build(deps): update dependencies&quot;</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/9472af9ca894215f0f2d7911ea677385c0425feb"><code>9472af9</code></a>
Revert &quot;build(execa): upgrade execa@9.5.2, require Node.js ^18.19.0
|| &gt;=20.5.0&quot;</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/9e17c9ce98bf8011b8f96f28fe82dfa7141868c3"><code>9e17c9c</code></a>
Revert &quot;chore: remove validation of deprecated advanced config
options&quot;</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/6fda79a81920f31b16b98085f0cc1b01f4db381c"><code>6fda79a</code></a>
Revert &quot;feat: remove <code>--shell</code> flag support&quot;</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/e1ea676ae5e9c730a8132617329c49f5956cf831"><code>e1ea676</code></a>
Revert &quot;feat: replace <code>execa</code> with
<code>nano-spawn</code>&quot;</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/556132176afce1701b4766c00ffd23159d437cb4"><code>5561321</code></a>
fix: handle colon characters in staged filenames (<a
href="https://redirect.github.com/lint-staged/lint-staged/issues/1544">#1544</a>)</li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/dcc9a51eb3714d15e3c4312a52fe7547412f4b9d"><code>dcc9a51</code></a>
feat: replace <code>execa</code> with <code>nano-spawn</code></li>
<li><a
href="https://github.com/lint-staged/lint-staged/commit/2fa909dc05ca0ed669e203bb8528cabf3d8426b0"><code>2fa909d</code></a>
feat: remove <code>--shell</code> flag support</li>
<li>Additional commits viewable in <a
href="https://github.com/lint-staged/lint-staged/compare/v15.3.0...v15.5.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/contentful/contentful-merge/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>